/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as testSmartContractWalletSol from "./TestSmartContractWallet.sol";
export type { testSmartContractWalletSol };
import type * as exchange from "./exchange";
export type { exchange };
import type * as lib from "./lib";
export type { lib };
import type * as registry from "./registry";
export type { registry };
import type * as static from "./static";
export type { static };
export type { Migrations } from "./Migrations";
export type { StaticMarket } from "./StaticMarket";
export type { TestAuthenticatedProxy } from "./TestAuthenticatedProxy";
export type { TestERC1155 } from "./TestERC1155";
export type { TestERC1271 } from "./TestERC1271";
export type { TestERC20 } from "./TestERC20";
export type { TestERC721 } from "./TestERC721";
export type { WyvernExchange } from "./WyvernExchange";
export type { WyvernRegistry } from "./WyvernRegistry";
export type { WyvernStatic } from "./WyvernStatic";
