/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface ExchangeInterfaceInterface extends utils.Interface {
  functions: {
    "approveOrder_(address,address,address,bytes4,bytes,uint256,uint256,uint256,uint256,bool)": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "approveOrder_"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "approveOrder_",
    values: [
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<string>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BytesLike>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "approveOrder_",
    data: BytesLike
  ): Result;

  events: {};
}

export interface ExchangeInterface extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: ExchangeInterfaceInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    approveOrder_(
      registry: PromiseOrValue<string>,
      maker: PromiseOrValue<string>,
      staticTarget: PromiseOrValue<string>,
      staticSelector: PromiseOrValue<BytesLike>,
      staticExtradata: PromiseOrValue<BytesLike>,
      maximumFill: PromiseOrValue<BigNumberish>,
      listingTime: PromiseOrValue<BigNumberish>,
      expirationTime: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      orderbookInclusionDesired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  approveOrder_(
    registry: PromiseOrValue<string>,
    maker: PromiseOrValue<string>,
    staticTarget: PromiseOrValue<string>,
    staticSelector: PromiseOrValue<BytesLike>,
    staticExtradata: PromiseOrValue<BytesLike>,
    maximumFill: PromiseOrValue<BigNumberish>,
    listingTime: PromiseOrValue<BigNumberish>,
    expirationTime: PromiseOrValue<BigNumberish>,
    salt: PromiseOrValue<BigNumberish>,
    orderbookInclusionDesired: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    approveOrder_(
      registry: PromiseOrValue<string>,
      maker: PromiseOrValue<string>,
      staticTarget: PromiseOrValue<string>,
      staticSelector: PromiseOrValue<BytesLike>,
      staticExtradata: PromiseOrValue<BytesLike>,
      maximumFill: PromiseOrValue<BigNumberish>,
      listingTime: PromiseOrValue<BigNumberish>,
      expirationTime: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      orderbookInclusionDesired: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    approveOrder_(
      registry: PromiseOrValue<string>,
      maker: PromiseOrValue<string>,
      staticTarget: PromiseOrValue<string>,
      staticSelector: PromiseOrValue<BytesLike>,
      staticExtradata: PromiseOrValue<BytesLike>,
      maximumFill: PromiseOrValue<BigNumberish>,
      listingTime: PromiseOrValue<BigNumberish>,
      expirationTime: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      orderbookInclusionDesired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    approveOrder_(
      registry: PromiseOrValue<string>,
      maker: PromiseOrValue<string>,
      staticTarget: PromiseOrValue<string>,
      staticSelector: PromiseOrValue<BytesLike>,
      staticExtradata: PromiseOrValue<BytesLike>,
      maximumFill: PromiseOrValue<BigNumberish>,
      listingTime: PromiseOrValue<BigNumberish>,
      expirationTime: PromiseOrValue<BigNumberish>,
      salt: PromiseOrValue<BigNumberish>,
      orderbookInclusionDesired: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
